/*
 * Copyright 2004-2013 ICEsoft Technologies Canada Corp.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS
 * IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.icemobile.spring.handler;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;

import org.icemobile.application.ByteArrayResource;
import org.icemobile.application.ResourceAdapter;
import org.icemobile.util.IOUtils;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartRequest;
import org.springframework.web.util.WebUtils;

/**
 * A ResourceAdapter to generate ByteArrayResources.
 * 
 * @see ByteArrayResource
 *
 */
public class ByteArrayResourceAdapter implements ResourceAdapter<ByteArrayResource>{

    /**
     * Process a request for resources and generate an array of ByteArrayResources.
     * 
     * @param request The servlet request to process.
     * @return An array of ByteArrayResources
     */
    public ByteArrayResource[] handleRequest(HttpServletRequest request) {
        MultipartRequest multipartRequest = WebUtils.getNativeRequest(request, MultipartRequest.class);
        List<ByteArrayResource> files = new ArrayList<ByteArrayResource>();
        if (multipartRequest != null) {
            Iterator<String> iter = multipartRequest.getFileNames();
            while( iter.hasNext() ){
                String fileName = iter.next();
                MultipartFile multipartFile = multipartRequest.getFile(fileName);
                if( !multipartFile.isEmpty() ){
                    try {
                        ByteArrayResource resource = new ByteArrayResource();
                        resource.setBytes(multipartFile.getBytes());
                        resource.setContentType(multipartFile.getContentType());
                        resource.setName(multipartFile.getName());
                        resource.setUiid(UUID.randomUUID().toString());
                        files.add(resource);
                    } catch (IOException e) {
                       e.printStackTrace();
                    }
                }
            }
        }    
        ByteArrayResource[] fileArray = new ByteArrayResource[files.size()];
        return files.toArray(fileArray);
    }

    /**
     * Process an InputStream for a resource.
     * 
     * @param is The InputStream to process.
     * @param contentType The content-type (mime-type) of the resource.
     * @return The generated ByteArrayResource
     */
    public ByteArrayResource handleInputStream(InputStream is, String contentType) {
        ByteArrayResource resource = null;
        ByteArrayOutputStream bos = null;
        try {
            bos = new ByteArrayOutputStream();
            IOUtils.copyStream(is, bos);
            resource = new ByteArrayResource();
            resource.setBytes(bos.toByteArray());
            resource.setContentType(contentType);
            resource.setUiid(UUID.randomUUID().toString());
            bos.close();
        } catch (IOException e) {
            e.printStackTrace();
        } finally{
            try {
                if( bos != null ){
                    bos.close();
                }
                if( is != null ){
                    is.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        
        return resource;
    }

}

