//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridgeit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bridgeit.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BridgeIt Camera Integration.
        /// </summary>
        public static string CameraAppBarAboutMenuItemMessage {
            get {
                return ResourceManager.GetString("CameraAppBarAboutMenuItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string CameraAppBarAboutMenuItemText {
            get {
                return ResourceManager.GetString("CameraAppBarAboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string CameraAppBarAcceptButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarAcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        public static string CameraAppBarBrowseButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string CameraAppBarCameraButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarCameraButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CameraAppBarCancelButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string CameraAppBarUploadButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarUploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo failed to upload {0}.
        /// </summary>
        public static string CameraAppProgresIndicatorFailure {
            get {
                return ResourceManager.GetString("CameraAppProgresIndicatorFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem uploading your photo.
        /// </summary>
        public static string CameraAppProgresIndicatorFailure2 {
            get {
                return ResourceManager.GetString("CameraAppProgresIndicatorFailure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading photo {0} %.
        /// </summary>
        public static string CameraAppProgressIndicator {
            get {
                return ResourceManager.GetString("CameraAppProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo upload canceled.
        /// </summary>
        public static string CameraAppProgressIndicatorCanceled {
            get {
                return ResourceManager.GetString("CameraAppProgressIndicatorCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo uploaded successfully.
        /// </summary>
        public static string CameraAppProgressIndicatorSuccess {
            get {
                return ResourceManager.GetString("CameraAppProgressIndicatorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.bridgeit.mobi/.
        /// </summary>
        public static string LaunchURL {
            get {
                return ResourceManager.GetString("LaunchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string SettingsCameraTitle {
            get {
                return ResourceManager.GetString("SettingsCameraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turned {0}.
        /// </summary>
        public static string SettingsGeneralSplashScreenSubText {
            get {
                return ResourceManager.GetString("SettingsGeneralSplashScreenSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splash screen.
        /// </summary>
        public static string SettingsGeneralSplashScreenText {
            get {
                return ResourceManager.GetString("SettingsGeneralSplashScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string SettingsGeneralTitle {
            get {
                return ResourceManager.GetString("SettingsGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go.
        /// </summary>
        public static string SettingsLaunchGoButtonText {
            get {
                return ResourceManager.GetString("SettingsLaunchGoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launch.
        /// </summary>
        public static string SettingsLaunchTitle {
            get {
                return ResourceManager.GetString("SettingsLaunchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url to load in Internet Explorer.
        /// </summary>
        public static string SettingsLaunchUriSubText {
            get {
                return ResourceManager.GetString("SettingsLaunchUriSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bridgeIt url.
        /// </summary>
        public static string SettingsLaunchUriText {
            get {
                return ResourceManager.GetString("SettingsLaunchUriText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bridgeit.github.io/demo/.
        /// </summary>
        public static string SettingsLaunchUriValue {
            get {
                return ResourceManager.GetString("SettingsLaunchUriValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SettingsSplashScreenOffTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SettingsSplashScreenOnTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsSplashScreenPageTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string SettingsSplashScreenStatusTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplashScreen.
        /// </summary>
        public static string SettingsSplashScreenTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIDGET SETTINGS.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
