//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridgeit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bridgeit.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string BarCodeScannerAccept {
            get {
                return ResourceManager.GetString("BarCodeScannerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the camera.
        /// </summary>
        public static string BarCodeScannerCameraError {
            get {
                return ResourceManager.GetString("BarCodeScannerCameraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BridgeIt Camera Integration.
        /// </summary>
        public static string CameraAppBarAboutMenuItemMessage {
            get {
                return ResourceManager.GetString("CameraAppBarAboutMenuItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string CameraAppBarAboutMenuItemText {
            get {
                return ResourceManager.GetString("CameraAppBarAboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string CameraAppBarAcceptButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarAcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        public static string CameraAppBarBrowseButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string CameraAppBarCameraButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarCameraButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CameraAppBarCancelButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string CameraAppBarUploadButtonText {
            get {
                return ResourceManager.GetString("CameraAppBarUploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo failed to upload {0}.
        /// </summary>
        public static string CameraAppProgresIndicatorFailure {
            get {
                return ResourceManager.GetString("CameraAppProgresIndicatorFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem uploading your photo.
        /// </summary>
        public static string CameraAppProgresIndicatorFailure2 {
            get {
                return ResourceManager.GetString("CameraAppProgresIndicatorFailure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading photo {0} %.
        /// </summary>
        public static string CameraAppProgressIndicator {
            get {
                return ResourceManager.GetString("CameraAppProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo upload cancelled.
        /// </summary>
        public static string CameraAppProgressIndicatorCanceled {
            get {
                return ResourceManager.GetString("CameraAppProgressIndicatorCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo uploaded successfully.
        /// </summary>
        public static string CameraAppProgressIndicatorSuccess {
            get {
                return ResourceManager.GetString("CameraAppProgressIndicatorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no results.
        /// </summary>
        public static string ContactsNoResults {
            get {
                return ResourceManager.GetString("ContactsNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results are loading....
        /// </summary>
        public static string ContactsResultsLoading {
            get {
                return ResourceManager.GetString("ContactsResultsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ContactsSearch {
            get {
                return ResourceManager.GetString("ContactsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people.
        /// </summary>
        public static string ContactsSubTitle {
            get {
                return ResourceManager.GetString("ContactsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIDGEIT.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string ContractsAccept {
            get {
                return ResourceManager.GetString("ContractsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ContractsCancel {
            get {
                return ResourceManager.GetString("ContractsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to device status.
        /// </summary>
        public static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Memory.
        /// </summary>
        public static string DeviceStatusApplicationMemoryUsage {
            get {
                return ResourceManager.GetString("DeviceStatusApplicationMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeviceStatusCancel {
            get {
                return ResourceManager.GetString("DeviceStatusCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Firmware Version.
        /// </summary>
        public static string DeviceStatusFirmwareVersion {
            get {
                return ResourceManager.GetString("DeviceStatusFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Version.
        /// </summary>
        public static string DeviceStatusHardwareVersion {
            get {
                return ResourceManager.GetString("DeviceStatusHardwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Present.
        /// </summary>
        public static string DeviceStatusKeyboard {
            get {
                return ResourceManager.GetString("DeviceStatusKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manufacturer.
        /// </summary>
        public static string DeviceStatusManufacturer {
            get {
                return ResourceManager.GetString("DeviceStatusManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryUsage Limit.
        /// </summary>
        public static string DeviceStatusMemoryUsageLimit {
            get {
                return ResourceManager.GetString("DeviceStatusMemoryUsageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Resolution .
        /// </summary>
        public static string DeviceStatusMultiResolution {
            get {
                return ResourceManager.GetString("DeviceStatusMultiResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceName.
        /// </summary>
        public static string DeviceStatusName {
            get {
                return ResourceManager.GetString("DeviceStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DeviceStatusNo {
            get {
                return ResourceManager.GetString("DeviceStatusNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DeviceStatusOK {
            get {
                return ResourceManager.GetString("DeviceStatusOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Memory Usuage.
        /// </summary>
        public static string DeviceStatusPeakMemoryUsage {
            get {
                return ResourceManager.GetString("DeviceStatusPeakMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Source.
        /// </summary>
        public static string DeviceStatusPowerSource {
            get {
                return ResourceManager.GetString("DeviceStatusPowerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIDGEIT .
        /// </summary>
        public static string DeviceStatusTitle {
            get {
                return ResourceManager.GetString("DeviceStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Total Memory.
        /// </summary>
        public static string DeviceStatusTotalMemory {
            get {
                return ResourceManager.GetString("DeviceStatusTotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DeviceStatusYes {
            get {
                return ResourceManager.GetString("DeviceStatusYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://10.18.39.175:8080/bridgeit/simplecamera.html.
        /// </summary>
        public static string LaunchURL {
            get {
                return ResourceManager.GetString("LaunchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string MicrophoneAcceptBtn {
            get {
                return ResourceManager.GetString("MicrophoneAcceptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound bite failed to upload {0}.
        /// </summary>
        public static string MicrophoneAppProgresIndicatorFailure {
            get {
                return ResourceManager.GetString("MicrophoneAppProgresIndicatorFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string MicrophoneCancelBtn {
            get {
                return ResourceManager.GetString("MicrophoneCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string MicrophonePlayBtn {
            get {
                return ResourceManager.GetString("MicrophonePlayBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem uploading your sound bite.
        /// </summary>
        public static string MicrophoneProgresIndicatorFailure2 {
            get {
                return ResourceManager.GetString("MicrophoneProgresIndicatorFailure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading sound bite {0} %.
        /// </summary>
        public static string MicrophoneProgressIndicator {
            get {
                return ResourceManager.GetString("MicrophoneProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound bite upload cancelled .
        /// </summary>
        public static string MicrophoneProgressIndicatorCanceled {
            get {
                return ResourceManager.GetString("MicrophoneProgressIndicatorCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.
        /// </summary>
        public static string MicrophoneRecordBtn {
            get {
                return ResourceManager.GetString("MicrophoneRecordBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record audio.
        /// </summary>
        public static string MicrophoneSubTitle {
            get {
                return ResourceManager.GetString("MicrophoneSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIDGEIT.
        /// </summary>
        public static string MicrophoneTitle {
            get {
                return ResourceManager.GetString("MicrophoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string MicrophoneUploadBtn {
            get {
                return ResourceManager.GetString("MicrophoneUploadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string SettingsCameraTitle {
            get {
                return ResourceManager.GetString("SettingsCameraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turned {0}.
        /// </summary>
        public static string SettingsGeneralSplashScreenSubText {
            get {
                return ResourceManager.GetString("SettingsGeneralSplashScreenSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splash screen.
        /// </summary>
        public static string SettingsGeneralSplashScreenText {
            get {
                return ResourceManager.GetString("SettingsGeneralSplashScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string SettingsGeneralTitle {
            get {
                return ResourceManager.GetString("SettingsGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go.
        /// </summary>
        public static string SettingsLaunchGoButtonText {
            get {
                return ResourceManager.GetString("SettingsLaunchGoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launch.
        /// </summary>
        public static string SettingsLaunchTitle {
            get {
                return ResourceManager.GetString("SettingsLaunchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url to load in Internet Explorer.
        /// </summary>
        public static string SettingsLaunchUriSubText {
            get {
                return ResourceManager.GetString("SettingsLaunchUriSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bridgeIt url.
        /// </summary>
        public static string SettingsLaunchUriText {
            get {
                return ResourceManager.GetString("SettingsLaunchUriText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bridgeit.github.io/demo/.
        /// </summary>
        public static string SettingsLaunchUriValue {
            get {
                return ResourceManager.GetString("SettingsLaunchUriValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SettingsSplashScreenOffTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SettingsSplashScreenOnTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsSplashScreenPageTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string SettingsSplashScreenStatusTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplashScreen.
        /// </summary>
        public static string SettingsSplashScreenTitle {
            get {
                return ResourceManager.GetString("SettingsSplashScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIDGEIT SETTINGS.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
